version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    container_name: hibernate-postgres
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'
  app:
    image: 'hibernate'
    container_name: 'HibernateStart.app'
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - '8080:8080'

